server:
  port: 3030
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7777/eureka
spring:
  application:
    name: SClient0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 538324202526-8uoqhsdtu1jb7nifb20v880f36u5r9b7.apps.googleusercontent.com
            client-secret: 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
